name: Digital-Hub CI-CD

on:
  push:
    branches: [ staging ]

jobs:
  build:
    name: Digital-Hub CI
    runs-on: ubuntu-latest
    
    steps:    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools==59.8.0
        python -m venv .venv
        . .venv/bin/activate
        python -m pip install -r requirements.txt

    - name: Run Tests
      run: |  
        python manage.py test apps/
    