version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e_commerce
    command: gunicorn -b 0.0.0.0:8000 core.wsgi:application
    volumes:
      - .:/E-Commerce-Graduation-Project
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: e_commerce_db
    env_file:
      - .env

    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
